FROM nimmis/spigot

COPY server /minecraft

ENV SPIGOT_VER=1.19
ENV MAVEN_VER=3.8.6

ENV LANG=en_US.UTF-8
ENV OTHER_JAVA_OPS=''
ENV EULA=true
ENV LANGUAGE=en_US:en
ENV HOSTNAME=ef510da65f98
ENV JAVA_HOME=/usr/lib/jvm/default-jvm
ENV JAVA_TYPE=''
ENV SPIGOT_AUTORESTART=yes
ENV JAVA_OPT=hotspot
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/default-jvm/bin/:/apache-maven-${MAVEN_VER}/bin
ENV MC_MAXMEM=''
ENV SPIGOT_HOME=/minecraft
ENV MC_MINMEM=''
ENV LC_ALL=en_US.UTF-8