FROM nimmis/spigot

ENV LANG=en_US.UTF-8
ENV OTHER_JAVA_OPS=''
ENV EULA=true
ENV LANGUAGE=en_US:en
ENV HOSTNAME=ef510da65f98
ENV JAVA_HOME=/usr/lib/jvm/default-jvm
ENV JAVA_TYPE=''
ENV SPIGOT_AUTORESTART=yes
ENV SPIGOT_VER=1.15.2
ENV JAVA_OPT=hotspot
ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/default-jvm/bin/
ENV MC_MAXMEM=''
ENV SPIGOT_HOME=/minecraft
ENV MC_MINMEM=''
ENV LC_ALL=en_US.UTF-8

RUN apt-get update -y && apt-get install -y maven